# Generated by Django 3.0.4 on 2020-05-10 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='signin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=120, unique=True)),
                ('phonenumber', models.CharField(max_length=16, unique=True)),
                ('password', models.CharField(max_length=16, unique=True)),
                ('password1', models.CharField(max_length=16, unique=True)),
            ],
        ),
    ]
