# Generated by Django 3.0.4 on 2020-03-29 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Addons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=10)),
                ('footer', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='BookDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10)),
                ('author', models.CharField(max_length=10)),
                ('addons', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='checking.Addons')),
            ],
        ),
    ]
