# Generated by Django 3.0.4 on 2020-05-02 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uactivity', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='activity',
            unique_together=set(),
        ),
    ]
