# Generated by Django 3.0.4 on 2020-05-03 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uactivity', '0002_auto_20200502_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterUniqueTogether(
            name='activity',
            unique_together={('user', 'start_time', 'end_time')},
        ),
    ]
